name: Pull GitHub Repository Contents and Deploy to Jenkins
 
on:
  push:
    branches: [main]
 
jobs:
  pull_repo_and_deploy:
    name: Pull GitHub Repository Contents and Deploy
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
 
      - name: Build Docker image
        run: docker build -t riyadm44/djangonewsimage:latest .
 
      - name: Push Docker image
        run: docker push riyadm44/djangonewsimage:latest
 
      - name: Create SSH directory
        run: mkdir -p ~/.ssh
 
      - name: Write private key to file
        run: echo "${{ secrets.KEY }}" > ~/.ssh/RHY.pem
 
      - name: Set permissions for private key file
        run: chmod 600 ~/.ssh/RHY.pem
 
      - name: Update known_hosts file
        run: ssh-keyscan -H 3.64.130.70 >> ~/.ssh/known_hosts
 
      - name: SSH into the server
        run: ssh -i ~/.ssh/RHY.pem ubuntu@3.64.130.70
 
      - name: Pull Docker image
        run: docker pull riyadm44/djangonewsimage:latest
 
      - name: Trigger Jenkins Pipeline
        run: |
          curl -X POST \
            -u YR:11f4a2c1e65b957ebf06ee90e9d53df9e6 \
            -d '' \
            http://3.64.130.70:8080/job/RY/build